spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
  servlet:
    session:
      # session过期时间秒
      timeout: 604800s
      cookie:
        # cookie max-age 过期时间秒(session id 存于cookie中)
        max-age: 604800s
# system:
# #客户端配置
  # client:
    # clients[0]:
      # clientId: OrderManagement
      # clientSecret: order123
    # clients[1]:
      # clientId: UserManagement
      # clientSecret: user123
    # clients[2]:
      # clientId: codeTest
      # clientSecret: order123