server:
  port: 8090
  servlet:
    context-path: /orderSystem   
    session:
      # session过期时间秒
      timeout: 604800s
      cookie:
        # cookie max-age 过期时间秒(session id 存于cookie中)
        max-age: 604800s
        path: /
        name: ORDERCLIENT
spring:
  redis:
    host: 127.0.0.1
    port: 6379

security:
  oauth2:
    client:
      client-id: OrderManagement
      client-secret: order123
      access-token-uri: http://myauth.com:8080/oauth/token
      user-authorization-uri: http://myauth.com:8080/oauth/authorize
    resource:
      token-info-uri: http://myauth.com:8080/oauth/check_token
      user-info-uri: http://myauth.com:8080/user
    authorization:
      check-token-access: http://myauth.com:8080/oauth/check_token
